### ISSUE TITLE
15. leaflet plugin for Omeka

### ISSUE THREAD

**Issue by knavickas** [BL-Labs/seasons#15]
https://www.acugis.com/blogs/new-leaflet-plugin-for-omeka/
Can we try this? 
Also, do I now have access to the server so I can access the back-end of the mapper website so I can upload e.g. plugins myself?

**Comment by benosteen** [comment]
We can but that is just a leaflet map with the usual suspects for source of map? eg OpenStreetmap, etc.

We need a map that can have points on it, and so on.

**Comment by knavickas** [comment]
o.k. just wondered if we could tweak it but if not, let's leave it. Thanks for having a look.

Katrina

Dr Katrina Navickas
Senior Lecturer in History,
School of Humanities Research Students' Tutor,
University of Hertfordshire,
De Havilland Campus, Hatfield, Herts, AL10 9AB.
01707 285624

http://about.me/katrina.navickas

**Comment by benosteen** [comment]
The tricky Omeka-y bit is the service that supplies points to put on that
map, which is where the Geolocation plugin comes in. It plugs in components
to store a geo point per item and a service to search for them for a given
area, and a display widget (which we'll edit) to display and browse them.

**Comment by knavickas** [comment]
o.k. understood.
