### ISSUE TITLE
3. how to layer these tiles onto the geolocator plugin map?

### ISSUE THREAD

**Issue by knavickas** [BL-Labs/seasons#3]
https://www.dropbox.com/sh/j4xbgk3dbzoxnxd/AACRbxCpiVs_rwRh_VYY0Vpva?dl=0

**Comment by benosteen** [comment]
Layering of any kind will need us to write the code to handle it! 2 scenarios:

1) we know what maps to overlay for a given meeting
  in that case, we can add this information to the meeting itself.

2) we want maps to overlay based on more general criteria - ie by year and for whatever region we are looking at.
 in this case, we would need some sort of tiling backend, such as that NLS example, to use instead of, or perhaps with, a modern map service like google maps.

**Comment by knavickas** [comment]
Hi ben,

See the email I've just sent about the meeting I've had with the NLS. I'm working on it!!!

Also going to meet the Space Syntax group at UCL this afternoon, so may be able to get more help there,

Katrina

Dr Katrina Navickas
Senior Lecturer in History,
School of Humanities Research Students' Tutor,
University of Hertfordshire,
De Havilland Campus, Hatfield, Herts, AL10 9AB.
01707 285624

http://about.me/katrina.navickas

**Comment by benosteen** [comment]
Good :) I've literally just got the email you mention! Good ole ridiculously slow email system.

**Comment by benosteen** [comment]
Using Leaflet should be nice and straightforward, and we can use the Geolocation plugin code as a basis for this but it will need low-level changes. It wouldn't be a case of changing a configuration setting I mean!

**Comment by benosteen** [comment]
Did they send the code snippet that you mentioned? Aboud getting the NLS
map to appear via leaflet? Or can they point at something on their sites
that might tell me how they expect people to reuse it?

**Comment by knavickas** [comment]
Ben,

I've got loads of stuff to send. In a meeting atmo in the cafe but will be down later,

Katrina

Dr Katrina Navickas
Senior Lecturer in History,
School of Humanities Research Students' Tutor,
University of Hertfordshire,
De Havilland Campus, Hatfield, Herts, AL10 9AB.
01707 285624

http://about.me/katrina.navickas

**Comment by knavickas** [comment]
Ben,

At the hot desk now, but won't disturb you.

See previous forwarded email from the NLS,

Katrina

Dr Katrina Navickas
Senior Lecturer in History,
School of Humanities Research Students' Tutor,
University of Hertfordshire,
De Havilland Campus, Hatfield, Herts, AL10 9AB.
01707 285624

http://about.me/katrina.navickas
